version: '3'
services:
  bokeh_app:
    build: .
    container_name: bokeh_app
    restart: always
    volumes:
      - ./bokeh/:/bokeh
      - ../app_data/:/app_data
    ports:
      - "5000:5000"
      - "5006:5006"
    env_file:
      - .env