version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.23.0
    container_name: reverse-proxy
    depends_on:
        - bokeh-app
        - tile-service
    volumes:
      - ./tiatoolbox/visualization/reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 20.0.0.9:8080:80

  # serves the bokeh app
  bokeh-app:
    image: bokeh-app
    container_name: bokeh-app
    build:
      context: .
      dockerfile: DockerfileB
    depends_on:
        - tile-service
    #ports:
     # - 5100:5100
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ../app_data/:/app_data


  # serves the tiles
  tile-service:
    image: tile-service
    container_name: tile-service
    build:
      context: .
      dockerfile: DockerfileTS
    #ports:
      #- 5000:5000
    restart: on-failure
    volumes:
      - ../app_data/:/app_data
