version: '3'
services:
  bokeh_app:
    build: .
    container_name: bokeh_app
    restart: always
    volumes:
      - ./bokeh/:/bokeh
      - ../app_data/:/app_data
    ports:
      - "20.0.0.9:5100:5100"
      - "5000:5000"
    env_file:
      - .env