version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy-demo:
    image: nginx:1.23.0
    container_name: reverse-proxy-demo
    depends_on:
        - demo-app
        - tile-service-demo
    volumes:
      - ./tiatoolbox/visualization/reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ../app_data/:/app_data
    ports:
      - 20.0.0.13:8080:80
    restart: on-failure
    networks:
      - tia-demos

  # serves the bokeh app
  demo-app:
    image: demo-app
    container_name: demo-app
    build:
      context: .
      dockerfile: DockerfileB
    depends_on:
        - tile-service-demo
    #ports:
    #  - 5100:5100
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ../app_data/:/app_data
      - ../app_data/:/tiatoolbox/tiatoolbox/visualization/bokeh_app/static
    networks:
      - tia-demos
    command: >
      sh -c "bokeh serve ./tiatoolbox/visualization/bokeh_app --enable-xsrf-cookies --auth-module=./tiatoolbox/visualization/bokeh_app/auth.py --log-level=debug --allow-websocket-origin="*" --port 5100 --use-xheaders --unused-session-lifetime 10000 --check-unused-sessions 5000 --keep-alive 0 --args /app_data"

  # serves the tiles
  tile-service-demo:
    image: tile-service-demo
    container_name: tile-service-demo
    build:
      context: .
      dockerfile: DockerfileTS
    #ports:
    #  - 5000:5000
    restart: on-failure
    volumes:
      - ../app_data/:/app_data
    networks:
      - tia-demos

networks:
  tia-demos:
